// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductGallery.Infrastructure.Data;

#nullable disable

namespace ProductGallery.Persistence.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230129225434_ChangeImageProduct")]
    partial class ChangeImageProduct
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductGallery.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a422b632-e3da-480f-b237-c551b14f84c0"),
                            CreatedAt = new DateTime(2023, 1, 29, 17, 54, 34, 263, DateTimeKind.Local).AddTicks(6480),
                            Name = "Computación"
                        },
                        new
                        {
                            Id = new Guid("b652bc42-9e7c-47dd-8331-73cfc3fee183"),
                            CreatedAt = new DateTime(2023, 1, 29, 17, 54, 34, 263, DateTimeKind.Local).AddTicks(6540),
                            Name = "Ropa"
                        },
                        new
                        {
                            Id = new Guid("1d643885-fe4b-4a90-8fae-a8218b80b915"),
                            CreatedAt = new DateTime(2023, 1, 29, 17, 54, 34, 263, DateTimeKind.Local).AddTicks(6560),
                            Name = "Accesorios"
                        },
                        new
                        {
                            Id = new Guid("a1ff8e63-2c4d-46b4-a684-595d389be365"),
                            CreatedAt = new DateTime(2023, 1, 29, 17, 54, 34, 263, DateTimeKind.Local).AddTicks(6570),
                            Name = "Libros"
                        },
                        new
                        {
                            Id = new Guid("a4745a21-cd2a-4b95-bc0b-a7ec9b12434f"),
                            CreatedAt = new DateTime(2023, 1, 29, 17, 54, 34, 263, DateTimeKind.Local).AddTicks(6580),
                            Name = "Cocina"
                        },
                        new
                        {
                            Id = new Guid("47ae148e-3623-46ba-a13e-995937216853"),
                            CreatedAt = new DateTime(2023, 1, 29, 17, 54, 34, 263, DateTimeKind.Local).AddTicks(6600),
                            Name = "Juegos"
                        },
                        new
                        {
                            Id = new Guid("5cb3774e-88e7-4d69-aac2-38e294f207ec"),
                            CreatedAt = new DateTime(2023, 1, 29, 17, 54, 34, 263, DateTimeKind.Local).AddTicks(6610),
                            Name = "Tecnología"
                        });
                });

            modelBuilder.Entity("ProductGallery.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("94a6a1b3-dfa8-4539-a262-31fb90c0cddf"),
                            CategoryId = new Guid("5cb3774e-88e7-4d69-aac2-38e294f207ec"),
                            CreatedAt = new DateTime(2023, 1, 29, 17, 54, 34, 263, DateTimeKind.Local).AddTicks(8130),
                            Name = "Iphone"
                        },
                        new
                        {
                            Id = new Guid("40ab51c4-d0c6-499d-b5ed-33def204cb32"),
                            CategoryId = new Guid("a1ff8e63-2c4d-46b4-a684-595d389be365"),
                            CreatedAt = new DateTime(2023, 1, 29, 17, 54, 34, 263, DateTimeKind.Local).AddTicks(8150),
                            Name = "Libro"
                        },
                        new
                        {
                            Id = new Guid("6795328d-1491-4c16-a2e4-c446004a9259"),
                            CategoryId = new Guid("a422b632-e3da-480f-b237-c551b14f84c0"),
                            CreatedAt = new DateTime(2023, 1, 29, 17, 54, 34, 263, DateTimeKind.Local).AddTicks(8160),
                            Name = "Computador"
                        },
                        new
                        {
                            Id = new Guid("cc05c8af-e70b-40ea-8bf1-e6d361be2ea8"),
                            CategoryId = new Guid("a422b632-e3da-480f-b237-c551b14f84c0"),
                            CreatedAt = new DateTime(2023, 1, 29, 17, 54, 34, 263, DateTimeKind.Local).AddTicks(8180),
                            Name = "Monitor"
                        },
                        new
                        {
                            Id = new Guid("922c3d52-a7df-45b2-a606-b2fdb5eee620"),
                            CategoryId = new Guid("a4745a21-cd2a-4b95-bc0b-a7ec9b12434f"),
                            CreatedAt = new DateTime(2023, 1, 29, 17, 54, 34, 263, DateTimeKind.Local).AddTicks(8190),
                            Name = "Cuchara"
                        },
                        new
                        {
                            Id = new Guid("d744cdcf-dd6f-4bb7-b39c-a91c3df296a1"),
                            CategoryId = new Guid("47ae148e-3623-46ba-a13e-995937216853"),
                            CreatedAt = new DateTime(2023, 1, 29, 17, 54, 34, 263, DateTimeKind.Local).AddTicks(8200),
                            Name = "Mario Kart"
                        });
                });

            modelBuilder.Entity("ProductGallery.Domain.Entities.Product", b =>
                {
                    b.HasOne("ProductGallery.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ProductGallery.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
