// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductGallery.Infrastructure.Data;

#nullable disable

namespace ProductGallery.Persistence.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230128202504_InitialData")]
    partial class InitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductGallery.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a422b632-e3da-480f-b237-c551b14f84c0"),
                            CreatedAt = new DateTime(2023, 1, 28, 15, 25, 4, 780, DateTimeKind.Local).AddTicks(8930),
                            Name = "Computación"
                        },
                        new
                        {
                            Id = new Guid("b652bc42-9e7c-47dd-8331-73cfc3fee183"),
                            CreatedAt = new DateTime(2023, 1, 28, 15, 25, 4, 780, DateTimeKind.Local).AddTicks(8970),
                            Name = "Ropa"
                        },
                        new
                        {
                            Id = new Guid("1d643885-fe4b-4a90-8fae-a8218b80b915"),
                            CreatedAt = new DateTime(2023, 1, 28, 15, 25, 4, 780, DateTimeKind.Local).AddTicks(8980),
                            Name = "Accesorios"
                        },
                        new
                        {
                            Id = new Guid("a1ff8e63-2c4d-46b4-a684-595d389be365"),
                            CreatedAt = new DateTime(2023, 1, 28, 15, 25, 4, 780, DateTimeKind.Local).AddTicks(8990),
                            Name = "Libros"
                        },
                        new
                        {
                            Id = new Guid("a4745a21-cd2a-4b95-bc0b-a7ec9b12434f"),
                            CreatedAt = new DateTime(2023, 1, 28, 15, 25, 4, 780, DateTimeKind.Local).AddTicks(9000),
                            Name = "Cocina"
                        },
                        new
                        {
                            Id = new Guid("47ae148e-3623-46ba-a13e-995937216853"),
                            CreatedAt = new DateTime(2023, 1, 28, 15, 25, 4, 780, DateTimeKind.Local).AddTicks(9010),
                            Name = "Juegos"
                        },
                        new
                        {
                            Id = new Guid("5cb3774e-88e7-4d69-aac2-38e294f207ec"),
                            CreatedAt = new DateTime(2023, 1, 28, 15, 25, 4, 780, DateTimeKind.Local).AddTicks(9010),
                            Name = "Tecnología"
                        });
                });

            modelBuilder.Entity("ProductGallery.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Image")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("ee0947fb-3b31-4104-918c-60ec99757d85"),
                            CategoryId = new Guid("5cb3774e-88e7-4d69-aac2-38e294f207ec"),
                            CreatedAt = new DateTime(2023, 1, 28, 15, 25, 4, 780, DateTimeKind.Local).AddTicks(9990),
                            Name = "Iphone"
                        },
                        new
                        {
                            Id = new Guid("1d4ce219-4369-4eee-a049-2e4fc02561d8"),
                            CategoryId = new Guid("a1ff8e63-2c4d-46b4-a684-595d389be365"),
                            CreatedAt = new DateTime(2023, 1, 28, 15, 25, 4, 781, DateTimeKind.Local),
                            Name = "Libro"
                        },
                        new
                        {
                            Id = new Guid("afcd4255-9860-48e0-aba0-5981a1857bbb"),
                            CategoryId = new Guid("a422b632-e3da-480f-b237-c551b14f84c0"),
                            CreatedAt = new DateTime(2023, 1, 28, 15, 25, 4, 781, DateTimeKind.Local).AddTicks(10),
                            Name = "Computador"
                        },
                        new
                        {
                            Id = new Guid("95654ed8-5510-4dbe-9b19-b267296f87e1"),
                            CategoryId = new Guid("a422b632-e3da-480f-b237-c551b14f84c0"),
                            CreatedAt = new DateTime(2023, 1, 28, 15, 25, 4, 781, DateTimeKind.Local).AddTicks(20),
                            Name = "Monitor"
                        },
                        new
                        {
                            Id = new Guid("b6353504-c6cc-4c87-8610-4c7eead3d16e"),
                            CategoryId = new Guid("a4745a21-cd2a-4b95-bc0b-a7ec9b12434f"),
                            CreatedAt = new DateTime(2023, 1, 28, 15, 25, 4, 781, DateTimeKind.Local).AddTicks(30),
                            Name = "Cuchara"
                        },
                        new
                        {
                            Id = new Guid("1b01ecb1-0e9d-4ddc-b09a-a0e1f1685c74"),
                            CategoryId = new Guid("47ae148e-3623-46ba-a13e-995937216853"),
                            CreatedAt = new DateTime(2023, 1, 28, 15, 25, 4, 781, DateTimeKind.Local).AddTicks(30),
                            Name = "Mario Kart"
                        });
                });

            modelBuilder.Entity("ProductGallery.Domain.Entities.Product", b =>
                {
                    b.HasOne("ProductGallery.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ProductGallery.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
